### ISSUE TITLE
ROUND, CEIL, FLOOR should not require returned datatype to be the same as argument datatype

### ISSUE THREAD

**Issue by wastl** [JulienNauroy/SPARQLScore#10]
The functions ROUND, CEIL and FLOOR return by their definition an integer number without fractional part. The SPARQL 1.1 specification only requires the return value to be "numeric" and not that it matches the type of the arguments. The tests should therefore in this case only check if the results are numeric.

**Comment by BorderCloud** [comment]
Hi
Thanks for the remark. My response : BorderCloud/TFT-tests#8
Bye
