### ISSUE TITLE
AVG should accept all numeric return types

### ISSUE THREAD

**Issue by wastl** [JulienNauroy/SPARQLScore#11]
The tests currently require that the result of AVG always is the same type as the input arguments. However, the SPARQL 1.1 specification defines AVG as to return any numeric value. The tests should therefore only check if the return type is numeric.

This also makes sense when you take e.g. the example of the average of the integers 1 and 2 - which is the double or decimal value 1.5.

**Comment by BorderCloud** [comment]
Hi
Thanks for the remark. My response here : BorderCloud/TFT-tests#9
Bye
