### ISSUE TITLE
Grid Observatory 10: date subtraction not defined by SPARQL 1.1

### ISSUE THREAD

**Issue by wastl** [JulienNauroy/SPARQLScore#7]
The test for date subtraction in test Grid Observatory does not conform to the SPARQL 1.1 specification. The operator "-" is only defined for numeric operands.

http://www.w3.org/TR/sparql11-query/#OperatorMapping

**Comment by BorderCloud** [comment]
Hi
Thanks for the remark. My response here : https://github.com/BorderCloud/TFT-tests/issues/6
Bye
