### ISSUE TITLE
SPARQL Syntax Tests: Status Code 400 for error should be honoured

### ISSUE THREAD

**Issue by wastl** [JulienNauroy/SPARQLScore#8]
For several of the SPARQL 1.1 syntax tests, the SPARQL testsuite simply contains a dummy result with a variable named "error", indicating that parsing is expected to fail. According to the SPARQL protocol, parse errors should return an HTTP result with status code 400 (Bad Request):

http://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-failure

The SPARQLScore tests need to be changed accordingly.

**Comment by BorderCloud** [comment]
Hi
Thanks for the remark. My response here : BorderCloud/TFT#1
Bye
