### ISSUE TITLE
JSON Result Tests: type "typed-literal" is invalid

### ISSUE THREAD

**Issue by wastl** [JulienNauroy/SPARQLScore#9]
The JSON tests expect typed results to have a field "type: 'typed-literal' ". According to the SPARQL JSON Protocol, such a value does not exist; it should be "type: 'literal'" instead:

http://www.w3.org/TR/2013/REC-sparql11-results-json-20130321/#select-encode-terms

**Comment by BorderCloud** [comment]
Hi
Thanks for the remark. My response here : BorderCloud/TFT-tests#7
Bye
